- hosts: localhost
  become: true
  
  tasks:
  - name: Add the Syncthing keys
    apt_key:
      url: https://syncthing.net/release-key.txt
      state: present

  - name: Install Syncthing
    apt_repository:
      repo: 'deb https://apt.syncthing.net/ syncthing stable'
      file: syncthing
      state: present

  - name: Install Wavebox Repo
    apt_repository:
      repo: 'deb [arch=amd64] https://download.wavebox.app/latest/stable/linux/deb/ stable main'       
      file: wavebox
      state: present

  - name: install software
    apt: name={{item}}
    with_items:
    - traceroute
    - git
    - vim
    - wavebox
    - syncthing 
