- hosts: localhost
  become: true
  
  tasks:
  - name: Add the Syncthing keys
    apt_key:
      url: https://syncthing.net/release-key.txt
      state: present

  - name: Install Syncthing
    apt_repository:
      repo: 'deb https://apt.syncthing.net/ syncthing stable'
      filename: syncthing
      state: present

  - name: Add the Lutris PPA
    apt_repository:
        repo: ppa:lutris-team/lutris

  - name: Add Wavebox
    apt:
      deb: https://download.wavebox.app/latest/stable/linux/deb

  - name: Updating the Apt Cache
    apt:
      update_cache: yes

  - name: install software
    apt: 
      name: "{{item}}"
      state: latest
    loop:
    - traceroute
    - git
    - vim
    - syncthing 
    - keepassxc
    - wine
    - lutris
    - libreoffice
    - simplenote
    - tilda
    - inkscape
    - gimp
